### ISSUE TITLE
Is the mean cube dataset-specific?

### ISSUE THREAD

**Issue by dshahrokhian** [axon-research/c3d-keras#10]
I am using C3D for a different task, so I was wondering if the `mean_cube` was calculated from UCF101 dataset.

**Comment by chuckcho** [comment]
Yes. It was calculated from UCF101 split1. For the most part, I haven't seen any difference between using mean cube, and using mean RGB, [90, 98, 102] (https://github.com/chuckcho/video-caffe/blob/master/examples/c3d_ucf101/c3d_ucf101_train_test.prototxt#L25-L31)

**Comment by dshahrokhian** [comment]
@chuckcho Thanks. I was considering using the dataset-specific mean, but then I saw instances in which C3D was used for labeling Youtube videos, and using the original `mean_cube` seemed to work just fine. In my case, I am not getting the performance I was expecting, so I am considering that alternative.
