### ISSUE TITLE
I can't find sports1M_weights_tf.h5 and sports1M_weights_tf.json

### ISSUE THREAD

**Issue by youssefoumate** [axon-research/c3d-keras#11]
Hello Sir,
```
FileNotFoundError: [Errno 2] No such file or directory: 'models/sports1M_weights_tf.json'
```
I can't find those two files !!

**Comment by chuckcho** [comment]
@youssefoumate it appears that `convert_caffe_model.py` didn't run successfully. What do you see when you run that?

**Comment by youssefoumate** [comment]
thank you sir for your reply 
I get this error : 
```
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'pool3/MaxPool3D' (op: 'MaxPool3D') with input shapes: [?,1,4,28,256].
```

**Comment by youssefoumate** [comment]
oh sorry sorry ! 
Actually I was using Keras version 2 
and this line : dim_ordering = K._image_dim_ordering
wasn't working for me 
so I change it to that : dim_ordering = K.image_dim_ordering
which wasn't a good idea :-1: 
but now I'm using Keras 1.2.0 
it works fine :)

**Comment by chuckcho** [comment]
Good to know it's now working. ;)

**Comment by huangjiapei** [comment]
hello!I cannot download sports1M_weights_tf.h5,could you send to me,1747199078@qq.com!Thank you.
