### ISSUE TITLE
OpenCV's incompatibility

### ISSUE THREAD

**Issue by raghavgoyal14** [axon-research/c3d-keras#13]
Hi,

Many thanks for this repo.
I ran the code, but got stuck due to ffmpeg inconsistencies which renders `cv2.VideoCapture()` unusable.

To get a workaround, I bursted frames from the video using:
```
ffmpeg -i dM06AMFLsrc.mp4 -vf scale=171:128 -r 25 -f image2 'vid_frames/%04d.jpg'
``` 
Then read it in the code using scipy.ndimage module:
```python
def load_video_clip():
    print("[Info] Loading a sample video...")
    path_to_vid = "/home/vid_frames/"
    vid = []
    for frame_num in range(2000, 2016):
        frame = scipy.ndimage.imread(path_to_vid + str(frame_num) + ".jpg")
        vid.append(frame)
    return np.array(vid, dtype=np.float32)
```

The point is that the bursted video frames looks same enough as in https://gist.github.com/albertomontesg/d8b21a179c1e6cca0480ebdf292c34d2.
But, the output I get is:
```
Position of maximum probability: 359
Maximum probability: 0.13669
Corresponding label: volleyball

Top 5 probabilities and labels:
volleyball: 0.13669
gaelic football: 0.08436
inline speed skating: 0.07865
roller derby: 0.06737
hurdles: 0.06567
```
What in your opinion might be causing this ?
Thanks again.

- Raghav

**Comment by raghavgoyal14** [comment]
Although, when I use opencv-python, I'm able to replicate the results.
For my video dataset, I'm using the above ffmpeg command to burst and save frames to feed into the input pipeline of tensorflow. On the other hand, is I use opencv then saving numpy object for bursted frames is a disadvantage in terms of storage capacity.

If possible, can you share how you go about it ?

**Comment by chuckcho** [comment]
Hope you figured out the way to deal with opencv. SInce this is not directly related to Keras implementation of C3D, I'm closing this issue.
