### ISSUE TITLE
Fine Tuning in Keras

### ISSUE THREAD

**Issue by farzaa** [axon-research/c3d-keras#16]
Hi! Thanks so much for doing this work, its already saved me a great deal of time since most of my stuff is built in Keras :)!

I'm attempting to fine tune this model for a completely different task, predicting steering angles from dash camera videos. I have the data: driving sequence images and steering angles with each frame. 40k total frames. Though, I'm having some issues and wanted to be sure it doesn't have anything to do with any limitation related to the model/weights your scripts output. 

Please note this is my first time fine tuning anything! I read a couple of blogs and such to get an idea but please be critical!

I decided to split the work into two main steps. 

Here was my plan of action:
1. Get model/weights from the work you did here.
2. Freeze all the layers.
3. Drop the final layer.
4. Add my own dense layer with one unit and a tanh activation function to predict a steering angle.

The code:
```
    json_file = open(orignal_model_path, 'r')
    loaded_model_json = json_file.read()
    json_file.close()

    model  = model_from_json(loaded_model_json)
    model.load_weights(orginal_weights_path)
    model.summary()
    model.pop()

    for layer in model.layers:
        layer.trainable = False

    model.add(Dense(1, activation='tanh', name='cutom')) 
```
5. Train (50 epochs) and save weights and save model. For my optimizer I used adam with a lr(0.0001).

The output I got from this step was already problematic. It was only predicting angles between 10 and 12 degrees. You can check out some of my logs here: http://imgur.com/a/zKTwY

Next:
6. Unfreeze all layers and load model/weights from step 5.
7. Train model again (50 epochs). For my optimizer I used SGD with a lr(0.0001).

The output I got from this layer actually just kept on outputting a single number for every single frames. Which means something went terribly wrong.

Any feedback on where you think I'm going wrong would be awesome!

**Comment by chuckcho** [comment]
sorry for the delayed response. i assume you converted the steering angle (in deg?) into [-1,1] range (i.e. min/max of tanh output). your training/val logs look ok to me.

**Comment by farzaa** [comment]
Hey there!

So I thought the same. But when I actually go to test, the network seems to only be predicting angles between 10 and 15 degrees. 

Any idea what could be up?

**Comment by chuckcho** [comment]
i'll leave this open for some time, but this is out of scope of this repo (Keras reimplemetation of C3D).

**Comment by chuckcho** [comment]
Closing this as this is outside the scope of this repo
