### ISSUE TITLE
Pretrained Models & Weights for TensorFlow

### ISSUE THREAD

**Issue by User-Ali** [axon-research/c3d-keras#18]
Can you please upload its trained model especial its weights on repo or send me on my personal email? I am on Windows and installing all these things are the heck process for me.

**Comment by chuckcho** [comment]
Please download the original model (provided by facebook/C3D repo) from here: https://github.com/axon-research/c3d-keras/blob/28ea685e8082358e8fb19063642d5c5dcf5856cc/models/get_weights_and_mean.sh#L10

**Comment by abhigyank** [comment]
I think the OP is asking for the Keras weights not the caffe.
