### ISSUE TITLE
about the sports1M_weights_tf.json

### ISSUE THREAD

**Issue by TouchSkyWf** [axon-research/c3d-keras#21]
Hello,I can't find the sports1M_weights_tf.json in you models, could u please tell me how to get this json? Thank you!!!

**Comment by chuckcho** [comment]
did you try `models/get_weights_and_mean.sh`? if that script didn't work, please check if you can download "http://vlg.cs.dartmouth.edu/c3d/conv3d_deepnetA_sport1m_iter_1900000"
