### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by dshahrokhian** [axon-research/c3d-keras#7]
```
Traceback (most recent call last):
  File "test_model.py", line 225, in <module>
    main()
  File "test_model.py", line 171, in main
    X = vid[start_frame:(start_frame + 16), :, :, :]
IndexError: too many indices for array
```

I have already checked the closed issue with this exact same problem. My opencv installation is correct since I already use it in other projects. Any ideas?

**Comment by chuckcho** [comment]
Could you start from if `vid` has all the video frames? What's `vid.shape`?

**Comment by dshahrokhian** [comment]
@chuckcho It contains no video frames `(0,)`

**Comment by chuckcho** [comment]
@dshahrokhian can you try to isolate the issue? e.g.
- is the input video file accessible?
- is the filename correct?
- can opencv load other videos?

**Comment by dshahrokhian** [comment]
The problem was at my IDE (Visual Studio Code) and the association with bin files... my bad.

**Comment by chuckcho** [comment]
Another reason to stay away from Windows machine. ;)
Glad it was resolved. :)
