### ISSUE TITLE
Training the network?

### ISSUE THREAD

**Issue by dshahrokhian** [axon-research/c3d-keras#8]
I was wondering if there is any work done towards being able to replicate the training. I am currently trying to adapt the network to 8 frames instead of 16, for which (as far as I know) the network needs to be trained from scratch.

**Comment by chuckcho** [comment]
We don't cover training component in this repo. This is rather how to convert Caffe-trained C3D model into Keras/TF format.
One way to customize training is to use the [original facebook/C3D repo](https://github.com/facebook/C3D). The issue board there should be able to better help you.
